/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;


import javax.swing.ImageIcon;
import util.ES;

/**
 *
 * @author LABINFO
 */
public class FrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenu
     * 
     */
    
    
    public FrameMenu() {
        initComponents();
        //this.setIconImage(new ImageIcon(getClass().getResource("/frames/clipboard-icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();
        menuRevisao = new javax.swing.JMenu();
        menuItemRevisao1 = new javax.swing.JMenuItem();
        menuItemRevisao2 = new javax.swing.JMenuItem();
        menuItemRevisao3 = new javax.swing.JMenuItem();
        menuItemRevisao4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuAluno = new javax.swing.JMenuItem();
        menuProfessor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exercícios de Java");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/yggdrasil.jpg"))); // NOI18N

        menuArquivo.setText("Arquivo");

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemSair);

        jMenuBar1.add(menuArquivo);

        menuRevisao.setText("Revisão");

        menuItemRevisao1.setText("Revisão 1");
        menuItemRevisao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRevisao1ActionPerformed(evt);
            }
        });
        menuRevisao.add(menuItemRevisao1);

        menuItemRevisao2.setText("Revisão 2");
        menuItemRevisao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRevisao2ActionPerformed(evt);
            }
        });
        menuRevisao.add(menuItemRevisao2);

        menuItemRevisao3.setText("Revisão 3");
        menuItemRevisao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRevisao3ActionPerformed(evt);
            }
        });
        menuRevisao.add(menuItemRevisao3);

        menuItemRevisao4.setText("Revisão 4");
        menuItemRevisao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRevisao4ActionPerformed(evt);
            }
        });
        menuRevisao.add(menuItemRevisao4);

        jMenuBar1.add(menuRevisao);

        jMenu1.setText("Herança");

        menuAluno.setText("Aluno");
        menuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(menuAluno);

        menuProfessor.setText("Professor");
        menuProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfessorActionPerformed(evt);
            }
        });
        jMenu1.add(menuProfessor);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRevisao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRevisao1ActionPerformed
        // TODO add your handling code here:
        
        FrameRevisao1 rev1=new FrameRevisao1();
        rev1.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuItemRevisao1ActionPerformed

    private void menuItemRevisao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRevisao2ActionPerformed
        // TODO add your handling code here:
        FrameRevisao2 rev2 = new FrameRevisao2();
        rev2.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuItemRevisao2ActionPerformed

    private void menuItemRevisao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRevisao4ActionPerformed
        // TODO add your handling code here:
        FrameRevisao4 rev4 = new FrameRevisao4();
        rev4.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuItemRevisao4ActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        // TODO add your handling code here:
        ES.mostrarMensagem("Finalizando o sistema", this);
        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemRevisao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRevisao3ActionPerformed
        // TODO add your handling code here:
        FrameRevisao3 rev3 = new FrameRevisao3();
        rev3.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuItemRevisao3ActionPerformed

    private void menuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfessorActionPerformed
        // TODO add your handling code here:
        FrameProfessor prof = new FrameProfessor();
        prof.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuProfessorActionPerformed

    private void menuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlunoActionPerformed
        // TODO add your handling code here:
        FrameAluno aluno = new FrameAluno();
        aluno.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_menuAlunoActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAluno;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuItemRevisao1;
    private javax.swing.JMenuItem menuItemRevisao2;
    private javax.swing.JMenuItem menuItemRevisao3;
    private javax.swing.JMenuItem menuItemRevisao4;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuProfessor;
    private javax.swing.JMenu menuRevisao;
    // End of variables declaration//GEN-END:variables
}
