CREATE DATABASE BDLIVRARIA;

CREATE TABLE AUTOR (
ID_AUTOR INT IDENTITY(1,1) NOT NULL,
CIDADE VARCHAR(45) NOT NULL,
GENERO VARCHAR(1) NOT NULL,
NOME VARCHAR(45) NOT NULL,
ESTADO VARCHAR(2) NOT NULL,
CONSTRAINT PK_AUTOR PRIMARY KEY(ID_AUTOR)
);
SELECT * FROM AUTOR;

INSERT INTO AUTOR(CIDADE, GENERO, NOME, ESTADO) VALUES ('TAUBATE', 'M', 'MONTEIRO LOBATO', 'SP');
INSERT INTO AUTOR(CIDADE, GENERO, NOME, ESTADO) VALUES ('RECIFE', 'M', 'MANUEL BANDEIRA', 'PE');

CREATE TABLE EDITORA(
ID_EDITORA INT IDENTITY(1,1) NOT NULL,
NOME VARCHAR(45) NOT NULL,
CIDADE VARCHAR(45) NOT NULL,
ESTADO VARCHAR(2) NOT NULL,
CONSTRAINT PK_EDITORA PRIMARY KEY(ID_EDITORA)
);
SELECT * FROM EDITORA;

INSERT INTO EDITORA(NOME, CIDADE, ESTADO) VALUES ('SARAIVA', 'RIO PRETO', 'SP');
INSERT INTO EDITORA(NOME, CIDADE, ESTADO) VALUES ('GLOBO', 'PORTO ALEGRE', 'RS');

CREATE TABLE LIVRO(
ID_LIVRO INT IDENTITY(1,1) NOT NULL,
DESCRICAO VARCHAR(45)NOT NULL,
QTDE INT NOT NULL,
VALOR DECIMAL NOT NULL,
COD_AUTOR INT NOT NULL,
COD_EDITORA INT NOT NULL,
CONSTRAINT PK_LIVRO PRIMARY KEY(ID_LIVRO),
CONSTRAINT FK_AUTOR FOREIGN KEY(COD_AUTOR) REFERENCES AUTOR(ID_AUTOR),
CONSTRAINT FK_EDITORA FOREIGN KEY(COD_EDITORA) REFERENCES EDITORA(ID_EDITORA)
);
SELECT * FROM LIVRO;

INSERT INTO LIVRO(DESCRICAO, QTDE, VALOR, COD_AUTOR, COD_EDITORA) VALUES ('SITIO DO PICA-PAU AMARELO', '25', 25.00, 1, 2);
INSERT INTO LIVRO (DESCRICAO, QTDE, VALOR, COD_AUTOR, COD_EDITORA) VALUES ('ESTRELA DO AMANHÃ', '19', 35.00, 2, 2);

SELECT L.DESCRICAO, A.NOME, L.DESCRICAO
FROM LIVRO L INNER JOIN AUTOR A ON L.COD_AUTOR = A.ID_AUTOR;

SELECT L.DESCRICAO, L.VALOR, E.NOME
FROM LIVRO L INNER JOIN EDITORA E ON L.COD_EDITORA = E.ID_EDITORA;

SELECT L.DESCRICAO, L.QTDE, L.VALOR, A.NOME
FROM LIVRO L INNER JOIN AUTOR A ON L.COD_AUTOR = A.ID_AUTOR;

SELECT L.DESCRICAO, E.NOME
FROM LIVRO L INNER JOIN EDITORA E ON L.COD_EDITORA = E.ID_EDITORA
WHERE L.QTDE>20;


