CREATE DATABASE BDESCOLA;


CREATE TABLE SALA_AULA (
ID_SALA_AULA INT NOT NULL IDENTITY(1,1),
NUMERO INT NOT NULL,
LOCAL VARCHAR (45),
CONSTRAINT PK_SALA PRIMARY KEY(ID_SALA_AULA));

--INSERÇÃO DE DADOS NA TABELA SALA_AULA
INSERT INTO SALA_AULA (NUMERO, LOCAL) VALUES (06, 'GALPÃO INFO');
INSERT INTO SALA_AULA (NUMERO, LOCAL) VALUES (04, 'GALPÃO PRINCIPAL');
--CONSULTA DE DADOS NA TABELA SALA_AULA
SELECT * FROM SALA_AULA;

CREATE TABLE TURMAS (
ID_TURMA INT NOT NULL IDENTITY(1,1),
DATA_HORA DATE NOT NULL,
MODULO_ANO VARCHAR (45) NOT NULL,
COD_SALA_AULA INT,
CONSTRAINT PK_TURMA PRIMARY KEY(ID_TURMA),
CONSTRAINT FK_SALA_AULA FOREIGN KEY (COD_SALA_AULA) REFERENCES SALA_AULA (ID_SALA_AULA));

--INSERÇÃO DE DADOS NA TABELA TURMAS
INSERT INTO TURMAS (DATA_HORA, MODULO_ANO, COD_SALA_AULA) VALUES ('2019-02-16', 'SEGUNDO MODULO', 1);
INSERT INTO TURMAS (DATA_HORA, MODULO_ANO, COD_SALA_AULA) VALUES ('2019-03-16', 'TERCEIRO MODULO', 2);
--CONSULTA DE DADOS NA TABELA TURMAS
SELECT * FROM TURMAS;

CREATE TABLE PROFESSORES (
ID_PROFESSOR INT NOT NULL IDENTITY(1,1),
NOME VARCHAR(45) NOT NULL,
CONSTRAINT PK_PROFESSOR PRIMARY KEY(ID_PROFESSOR));
--INSERÇÃO DE DADOS NA TABELA PROFESSORES
INSERT INTO PROFESSORES (NOME) VALUES ('MARCOS GONSALVES');
INSERT INTO PROFESSORES (NOME) VALUES ('VINICIUS DE ALENCAR');
--CONSULTA DE DADOS NA TABELA PROFESSORES
SELECT * FROM PROFESSORES;

CREATE TABLE ALUNOS (
ID_ALUNO INT NOT NULL IDENTITY(1,1),
NOME VARCHAR(45) NOT NULL,
IDADE INT NOT NULL,
ENDERECO VARCHAR(45),
CIDADE VARCHAR (45),
COD_TURMA INT,
CONSTRAINT PK_ALUNO PRIMARY KEY(ID_ALUNO),
CONSTRAINT FK_COD_TURMA FOREIGN KEY (COD_TURMA) REFERENCES TURMAS(ID_TURMA));
--INSERÇÃO DE DADOS NA TABELA ALUNOS
INSERT INTO ALUNOS (NOME, IDADE, ENDERECO, CIDADE, COD_TURMA) VALUES ('GUILHERME PIOVEZAN', 18, 'AVENIDA SÃO PAULO', 'JOSÉ BONIFÁCIO', 1);
INSERT INTO ALUNOS (NOME, IDADE, ENDERECO, CIDADE, COD_TURMA) VALUES ('IVAN SOUZA', 28, 'RUA MOGINI DAS CRUZES', 'ITABAPUÃ', 2);
--CONSULTA DE DADOS NA TABELA ALUNOS
SELECT * FROM ALUNOS;

CREATE TABLE MATERIAS (
ID_MATERIA INT NOT NULL IDENTITY(1,1),
NOME VARCHAR(45) NOT NULL,
COD_PROFESSOR INT,
COD_ALUNO INT,
CONSTRAINT PK_MATERIA PRIMARY KEY(ID_MATERIA),
CONSTRAINT FK_COD_PROFESSOR FOREIGN KEY (COD_PROFESSOR) REFERENCES PROFESSORES(ID_PROFESSOR),
CONSTRAINT FK_COD_ALUNO FOREIGN KEY (COD_ALUNO) REFERENCES ALUNOS(ID_ALUNO));

--INSERÇÃO DE DADOS NA TABELA MATERIAS
INSERT INTO MATERIAS(NOME, COD_ALUNO, COD_PROFESSOR) VALUES ('BIOLOGIA', 1, 1);
INSERT INTO MATERIAS(NOME, COD_ALUNO, COD_PROFESSOR) VALUES ('EDUCAÇÃO FÍSICA', 2, 1);
--CONSULTA DE DADOS NA TABELA MATERIAS
SELECT * FROM MATERIAS;
