CREATE DATABASE BDLOCACAO;

CREATE TABLE TBCLIENTES
(
   IDCLI INT PRIMARY KEY NOT NULL IDENTITY(1,1),
   NOMECLI VARCHAR (30) NOT NULL,
   NASCLI DATE NOT NULL,
   TELCLI VARCHAR (14) NOT NULL,
   ENDECLI VARCHAR(40),
   BAIRROCLI VARCHAR (25),
   CIDADECLI VARCHAR (25),
   ESTADOCLI VARCHAR (2)
 );

--EXCLUIR TABELA
DROP TABLE TBCLIENTES;

--INSERÇÃO DE DADOS
INSERT INTO TBCLIENTES (NOMECLI, NASCLI, TELCLI, ENDECLI, BAIRROCLI, CIDADECLI, ESTADOCLI) VALUES ('Maria', '12/05/1994','(17)981234255', 'Rua 1', 'JD.Congonhas', 'Rio Preto', 'SP');
INSERT INTO TBCLIENTES VALUES ('João', '05/04/1978','(17)32224567', 'Rua 3', 'Centro', 'Cedral', 'SP');
INSERT INTO TBCLIENTES VALUES ('João Pedro', '10/05/1997','(32)32564377', 'Av. 5', 'Soraia', 'Rio das Pedras', 'MG');
INSERT INTO TBCLIENTES VALUES ('Pedro', '20/02/1995','(17)32219085', 'Av. 2', 'Bosque', 'Mirassol', 'SP');
INSERT INTO TBCLIENTES VALUES ('Ana', '04/05/1998','(17)987342209', 'Rua 3', 'Centro', 'Cedral', 'SP');
INSERT INTO TBCLIENTES VALUES ('Ana Maria', '24/03/1968','(17)987343387', 'Rua 5', 'Centro', 'Rio Preto', 'SP');

--SELEÇÃO DE DADOS
SELECT *FROM TBCLIENTES;



 CREATE TABLE TBAUTO
 (
   IDAUTO INT PRIMARY KEY NOT NULL IDENTITY (1,1),
   NOMEAUTO VARCHAR(15) NOT NULL,
   MARCAAUTO VARCHAR (10) NOT NULL,
   ANOAUTO INT NOT NULL,
   CORAUTO VARCHAR (15) NOT NULL,
   CATEGORIA VARCHAR (10)

 );
 -- EXCLUIR TABELA
 DROP TABLE TBAUTO;

 --INSERÇAÕ DE DADOS
 INSERT INTO TBAUTO (NOMEAUTO, MARCAAUTO, ANOAUTO,CORAUTO,CATEGORIA) VALUES( 'Uno', 'FIAT', 2016, 'branca', 'padrão');
 INSERT INTO TBAUTO (NOMEAUTO, MARCAAUTO, ANOAUTO,CORAUTO,CATEGORIA) VALUES( 'Gol', 'VOLKS', 2017, 'preta', 'padrão');
 INSERT INTO TBAUTO (NOMEAUTO, MARCAAUTO, ANOAUTO,CORAUTO,CATEGORIA) VALUES( 'Palio', 'FIAT', 2016, 'prata', 'Conforto');
 INSERT INTO TBAUTO (NOMEAUTO, MARCAAUTO, ANOAUTO,CORAUTO,CATEGORIA) VALUES( 'Colorolla', 'TOYOTA', 2015, 'prata', 'Luxo');

 --SELEÇÃO DE DADOS
 SELECT *FROM TBAUTO;


 CREATE TABLE TBLOCA
 (
    IDLOCA INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	CODCLI INT REFERENCES TBCLIENTES(IDCLI) NOT NULL,
	CODAUTO INT REFERENCES TBAUTO(IDAUTO) NOT NULL,
	RETIRADA DATE,
	ENTREGA DATE,
	VALORLOCA DECIMAL (5,2)

 );

 --EXCLUIR TABELA
 DROP TABLE TBLOCA;

 --INSEÇÃO DE DADOS;
 INSERT INTO TBLOCA (CODCLI, CODAUTO, RETIRADA, ENTREGA, VALORLOCA) VALUES (3,2,'24/08/2018','26/08/2018',160.00);
 INSERT INTO TBLOCA (CODCLI, CODAUTO, RETIRADA, ENTREGA, VALORLOCA) VALUES (1,1,'06/09/2018','09/09/2018',320.00);
 INSERT INTO TBLOCA (CODCLI, CODAUTO, RETIRADA, ENTREGA, VALORLOCA) VALUES (1,4,'10/09/2018','11/09/2018',320.00);
 INSERT INTO TBLOCA (CODCLI, CODAUTO, RETIRADA, ENTREGA, VALORLOCA) VALUES (4,3,'01/09/2018','02/09/2018',200.00);
 INSERT INTO TBLOCA (CODCLI, CODAUTO, RETIRADA, ENTREGA, VALORLOCA) VALUES (2,3,'04/09/2018','06/09/2018',300.00);
 INSERT INTO TBLOCA (CODCLI, CODAUTO, RETIRADA, ENTREGA, VALORLOCA) VALUES (5,2,'06/09/2018','08/09/2018',240.00);
 INSERT INTO TBLOCA (CODCLI, CODAUTO, RETIRADA, ENTREGA, VALORLOCA) VALUES (6,1,'10/09/2018','11/09/2018',160.00);

 --SELEÇÃO DE DADOS
 SELECT * FROM TBLOCA;
 



 --7)	Consultar todos os carros da frota que são modelo 2016 e 2017.
 SELECT * FROM TBAUTO WHERE ANOAUTO BETWEEN  2016 AND 2017;

 --8)	Consultar nome, endereço e cidade de clientes moradores de Mirassol e que nasceram antes de 1994.
 SELECT NOMECLI, ENDECLI, CIDADECLI FROM TBCLIENTES WHERE CIDADECLI = 'Mirassol' AND NASCLI< '01/01/1994';

 --9)	Consultar nome e cidade de clientes que contenham “PEDRO” no nome.
 SELECT NOMECLI, CIDADECLI FROM TBCLIENTES WHERE NOMECLI LIKE '%Pedro%';

-- 10)	Consultar dados de locações que ocorreram no Mês de setembro de 2018.
 SELECT *FROM TBLOCA WHERE ENTREGA BETWEEN '01/09/2018' AND '30/09/2018';
 SELECT * FROM TBLOCA WHERE RETIRADA LIKE '%2018-09%';

--11)	Listar todas as marcas de automóveis sem repetição.
SELECT DISTINCT MARCAAUTO FROM TBAUTO;

--12)	Listar os dados de clientes moradores das cidades de Cedral e Rio Preto.
SELECT *FROM TBCLIENTES WHERE CIDADECLI IN('Cedral', 'Rio Preto');
SELECT *FROM TBCLIENTES WHERE CIDADECLI= 'Cedral' OR CIDADECLI = 'Rio Preto';

--13)	Listar dados de locações que tenham o valor da locação entre 160 e 200 reais
SELECT *FROM TBLOCA WHERE VALORLOCA>=160.00 AND VALORLOCA<=200.00;

--14)	Listar dados de automóveis que sejam da categoria padrão e da cor branca.
SELECT * FROM TBAUTO WHERE CATEGORIA = 'padrão' AND CORAUTO = 'BRANCA';

--15)	Listar dados de automóveis que sejam da categoria padrão mas não sejam da cor preta.
SELECT * FROM TBAUTO WHERE CATEGORIA = 'PADRÃO' AND CORAUTO <> 'PRETA';
SELECT * FROM TBAUTO WHERE CATEGORIA = 'PADRÃO' AND CORAUTO NOT LIKE '%PRETA%';

--16)	Listar nome e telefone de clientes dos estado de São Paulo que nasceram no ano de 1998.
SELECT NOMECLI, TELCLI FROM TBCLIENTES WHERE ESTADOCLI = 'SP' AND NASCLI LIKE  '%1998%';

--17)	Listar nome, telefone e endereço de clientes que não são moradores do estado de São Paulo.
SELECT NOMECLI, TELCLI FROM TBCLIENTES WHERE ESTADOCLI <> 'SP';


