CREATE DATABASE BDTRUFAS;

CREATE TABLE TBCLIENTES
( 
  ID_CLIENTE INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
  NOME_CLI VARCHAR (40) NOT NULL,
  TEL_CLI  VARCHAR (13),
  TIPO_CLI VARCHAR (13),
  EMAIL_CLI VARCHAR (35)
);

--COMANDO PARA EXCLUIR TBCLIENTES
DROP TABLE TBCLIENTES;

--COMANDO PARA BUSCAR DADOS DA TABELA TBCLIENTES
SELECT *FROM TBCLIENTES;

--COMANDO PARA INSERIR DADOS NA TBCLIENTES
INSERT INTO TBCLIENTES (NOME_CLI, TEL_CLI, TIPO_CLI, EMAIL_CLI) VALUES ('Maria Vieira', '(17)33438977', 'Amigo', 'ma.vieira234@hotmail.com');
INSERT INTO TBCLIENTES VALUES ('João Pedro', '', 'trabalho','');
INSERT INTO TBCLIENTES VALUES ('João Paulo', '(17)983432211', 'Amigo','');
INSERT INTO TBCLIENTES VALUES ('Fernanda', '(17)32334566', 'Amigo','fernandinha123@gmail.com');
INSERT INTO TBCLIENTES VALUES ('Ferdinando', '', 'Trabalho','');


CREATE TABLE TBPRODUTOS
(
  ID_PRO INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
  NOME_PROD VARCHAR (25),
  SABOR_PROD VARCHAR (25),
  QTD_PROD INTEGER,
  PRECO_PROD DECIMAL (4,2) NOT NULL,
  VAL_PROD DATE NOT NULL

);
--EXCLUIR TABELA
DROP TABLE TBPRODUTOS;

--BUSCAR DADOS
SELECT *FROM TBPRODUTOS;

--INSERÇÃO DE DADOS
 INSERT INTO TBPRODUTOS (NOME_PROD, SABOR_PROD, QTD_PROD,PRECO_PROD, VAL_PROD) VALUES ('Trufa Tradicional', 'Brigadeiro', 30, 4.50, '28/08/2018');
 INSERT INTO TBPRODUTOS VALUES	 ('Mini trufa', 'Brigadeiro', 220, 2.50, '28/08/2018'); 
 INSERT INTO TBPRODUTOS VALUES	 ('Trufa Tradicional', 'Ninho', 30, 4.50, '28/08/2018'); 
 INSERT INTO TBPRODUTOS VALUES	 ('Trufa Tradicional','Cereja', 30, 4.50, '28/08/2018');
 INSERT INTO TBPRODUTOS VALUES	 ('Mini trufa', 'Ninho', 220, 2.50, '28/08/2018');
 INSERT INTO TBPRODUTOS VALUES	 ('Trufa Festa', 'Cereja', 100, 2.00, '28/08/2018');
 INSERT INTO TBPRODUTOS VALUES	 ('Trufa Festa', 'Ninho', 100, 2.00, '28/08/2018');

 CREATE TABLE TBPEDIDOS
 (
   ID_PEDIDO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   COD_CLI INT REFERENCES TBCLIENTES(ID_CLIENTE) NOT NULL,
   ENTREGA DATE NOT NULL,
   FORM_PAG VARCHAR (15)
 );

 --EXCLUIR TABELA
 DROP TABLE TBPEDIDOS;

 --BUSCAR DADOS 
 SELECT *FROM TBPEDIDOS;

 --INSERÇÃO DE DADOS
 INSERT INTO TBPEDIDOS (COD_CLI, ENTREGA, FORM_PAG) VALUES (2, '2018/08/20', 'Dinheiro');
 INSERT INTO TBPEDIDOS VALUES (3, '2018/08/20', 'Débito');
 INSERT INTO TBPEDIDOS VALUES (5, '2018/08/17', 'Dinheiro');
 INSERT INTO TBPEDIDOS VALUES (4, '2018/08/18', 'Dinheiro');
 INSERT INTO TBPEDIDOS VALUES (3, '2018/08/25', 'Crédito');
 INSERT INTO TBPEDIDOS VALUES (1, '2018/08/16', 'Dinheiro');


 CREATE TABLE TBITENSPED
 (
   ID_ITEM INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   COD_PED INT REFERENCES TBPEDIDOS (ID_PEDIDO),
   COD_PROD INT REFERENCES TBPRODUTOS (ID_PRO),
   QTDE_ITEM INT NOT NULL
 );
 --EXCLUIR TABELA
 DROP TABLE TBITENSPED;

 --BUSCA DE DADOS 
 SELECT *FROM TBITENSPED;

 --INSERÇÃO DE DADOS
 INSERT INTO TBITENSPED VALUES (1,1,5);
 INSERT INTO TBITENSPED VALUES (1,3,5);
 INSERT INTO TBITENSPED VALUES (2,5,30);
 INSERT INTO TBITENSPED VALUES (2,2,30);
 INSERT INTO TBITENSPED VALUES (3,6,50);
 INSERT INTO TBITENSPED VALUES (4,4,6);
 INSERT INTO TBITENSPED VALUES (5,4,2);
 INSERT INTO TBITENSPED VALUES (6,1,5);
 


 --COMANDO PARA BUSCAR NOME E TIPO DE CLIENTE DE ID IGUAL A 3
 SELECT ID_CLIENTE, NOME_CLI, TIPO_CLI FROM TBCLIENTES WHERE ID_CLIENTE = 1;
 SELECT ID_PEDIDO, ENTREGA FROM TBPEDIDOS WHERE COD_CLI=2;
 SELECT ID_PEDIDO, ENTREGA FROM TBPEDIDOS WHERE COD_CLI=3;
 SELECT ID_PEDIDO, ENTREGA FROM TBPEDIDOS WHERE COD_CLI=4;
 SELECT NOME_CLI, TEL_CLI, EMAIL_CLI,TIPO_CLI FROM TBCLIENTES WHERE TIPO_CLI<>'amigo';
 SELECT NOME_CLI, TEL_CLI, EMAIL_CLI,TIPO_CLI FROM TBCLIENTES WHERE TIPO_CLI<>'trabalho';
 SELECT * FROM TBPRODUTOS WHERE SABOR_PROD = 'Cereja' AND NOME_PROD= 'Trufa Tradicional';
 SELECT * FROM TBPRODUTOS WHERE ID_PRO=2OR ID_PRO=3;
 SELECT * FROM TBPRODUTOS WHERE SABOR_PROD = 'Cereja' OR NOME_PROD= 'Trufa Tradicional' OR PRECO_PROD = 4.50;

 --Pesquisar nome de todos os clientes do tipo amigo
 SELECT NOME_CLI,TIPO_CLI FROM TBCLIENTES WHERE TIPO_CLI = 'amigo';

 --Pesquisar nome e preço dos produtos de sabor brigadeiro
 SELECT NOME_PROD, PRECO_PROD FROM TBPRODUTOS WHERE SABOR_PROD = 'BRIGADEIRO';

 --Pesquisar o nome e preço dos produtos que não tenham sabor cereja
 SELECT NOME_PROD, PRECO_PROD FROM TBPRODUTOS WHERE SABOR_PROD <> 'Cereja';

 --Pesquisar o ID, nome e sabor do produtos com preço acima de 4 reais
 SELECT ID_PRO, NOME_PROD, SABOR_PROD FROM TBPRODUTOS WHERE PRECO_PROD > 4.00;

 --Pesquisar nome e sabor dos produtos que possuem vencimento entre 26/08/2018 e 30/08/2018
 SELECT NOME_PROD, SABOR_PROD FROM TBPRODUTOS WHERE VAL_PROD > '26/08/2018' AND VAL_PROD< '30/08/2018';

 --Pesquisar ID, código do cliente e data de entrega para pedidos que tenham pagamento em dinheiro e data de entrega 20/08/2018
 SELECT ID_PEDIDO, COD_CLI, ENTREGA FROM TBPEDIDOS WHERE FORM_PAG = 'Dinheiro' AND ENTREGA = '2018/08/20';

 --Pesquisar todos os pedidos do cliente de ID=2 retornando a data do pedido e forma de pagamento
 SELECT FORM_PAG,ENTREGA FROM TBPEDIDOS WHERE COD_CLI = 2;

 --Pesquisar todos os itens do pedido de Id=6
 SELECT *FROM TBITENSPED WHERE COD_PED = 6;

 --Pesquisar todos os itens dos pedidos entre 4 e 7
 SELECT *FROM TBITENSPED WHERE COD_PED>=4 AND COD_PED<7;

 --Pesquisar todos os pedidos dos clientes de ID 3 e 5
 SELECT *FROM TBPEDIDOS WHERE COD_CLI=3 OR COD_CLI=5;

 --SELECIONANDO OS PRODUTOS DA TABELA PRODUTO
 SELECT DISTINCT NOME_PROD FROM TBPRODUTOS;

SELECT *FROM  TBITENSPED WHERE COD_PED BETWEEN 4 AND 7;

SELECT NOME_PROD, SABOR_PROD FROM TBPRODUTOS WHERE VAL_PROD BETWEEN '26/08/2018' AND '30/08/2018';

SELECT NOME_PROD, SABOR_PROD, VAL_PROD FROM TBPRODUTOS WHERE NOME_PROD IN ('TRUFA TRADICIONAL', 'MINI TRUFA');

SELECT NOME_PROD FROM TBPRODUTOS WHERE NOME_PROD LIKE 'TRUFA%';
SELECT DISTINCT  NOME_PROD FROM TBPRODUTOS WHERE NOME_PROD LIKE 'TRUFA%';
SELECT SABOR_PROD, NOME_PROD FROM TBPRODUTOS WHERE SABOR_PROD LIKE '%BRIG%';
SELECT NOME_PROD, SABOR_PROD FROM TBPRODUTOS WHERE SABOR_PROD LIKE '%NHO';
SELECT NOME_PROD, SABOR_PROD FROM TBPRODUTOS WHERE SABOR_PROD NOT LIKE '%NHO';




--Buscar os tipos de produtos de modo a não repetir o nome.
SELECT DISTINCT NOME_PROD FROM TBPRODUTOS;

--Buscar entregas entre 25/08/2018 e 01/09/2018.
SELECT ENTREGA FROM TBPEDIDOS WHERE ENTREGA BETWEEN '2018/08/25' AND '2018/09/01';

--Buscar produto onde o nome seja trufa tradicional ou mini trufa.
SELECT NOME_PROD FROM TBPRODUTOS WHERE NOME_PROD IN ('MINI TRUFA', 'TRUFA TRADICIONAL');

--Buscar nome de clientes que tenham o nome começando com J.
SELECT NOME_CLI FROM TBCLIENTES WHERE NOME_CLI LIKE 'J%';

--Buscar nome de cliente que termine com Pedro.
SELECT NOME_CLI FROM TBCLIENTES WHERE NOME_CLI LIKE '%PEDRO';

--Buscar dados dos pedidos que tenham forma de pagamento em débito ou dinheiro.
SELECT * FROM TBPEDIDOS WHERE FORM_PAG IN ('DÉBITO', 'DINHEIRO');
SELECT * FROM TBPEDIDOS WHERE FORM_PAG NOT LIKE 'CRÉDITO';

--Buscar nome e preço de produto que tenham sabor contendo “cer”.
SELECT NOME_PROD, PRECO_PROD FROM TBPRODUTOS WHERE SABOR_PROD LIKE '%CER%'; 

--SELECIONA NOME DE CLIENTES ONDE COMEÇAM POR F E SEJAM DO TIPO DE CLIENTES AMIGOS.
SELECT NOME_CLI FROM TBCLIENTES WHERE NOME_CLI LIKE 'F%' AND TIPO_CLI = 'AMIGO';


--SELECIONAR NOME, SABOR E PREÇO DE PRODUTOS QUE TENHAM PREÇO ACIMA DE R$ 3,00 E SEJAM DE SABOR NINHO OU BRIGADEIRO.
SELECT NOME_PROD, SABOR_PROD, PRECO_PROD FROM TBPRODUTOS WHERE PRECO_PROD>3.00 AND SABOR_PROD = 'NINHO' OR SABOR_PROD = 'BRIGADEIRO';

--SELECIONAR DADOS DO PRODUTO QUE CONTENHAM QUANTIDADE ENTRE 15 E 50 ITENS.
SELECT * FROM TBPRODUTOS WHERE QTD_PROD BETWEEN 15 AND 50;


--SELECIONAR PEDIDOS COM ENTREGA ENTRE 20-08-2018 E 25-08-2018 E COM FORMA DE PAGAMENTO EM CRÉDITO.

SELECT * FROM TBPEDIDOS WHERE ENTREGA BETWEEN '20-08-2018' AND '25-08-2018' AND FORM_PAG IN ('CRÉDITO');

