-- CRIAÇÃO DE BANCO DE DADOS 
CREATE DATABASE BDCONTATOS; 

--CRIAÇÃO DA TABELA CONTATOS
CREATE TABLE TBCONTATOS
(
 ID_CONTATO INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
 ENDERECO VARCHAR(30),
 CLASSE VARCHAR(15),
 NOME VARCHAR(20) NOT NULL 
);

--COMANDO PARA BUSCAR TODOS OS DADOS DA TABELA TBCONTATOS
SELECT *FROM TBCONTATOS;

--COMANDO PARA APAGAR TABELA
DROP TABLE TBCONTATOS; 

--INSERINDO DADOS NA TABELA TBCONTATOS SEM SEGUIR ESTRUTURA DE CRIAÇÃO
INSERT INTO TBCONTATOS (ENDERECO, CLASSE, NOME) VALUES ('Rua 1','Familía','Maria Flores');
--INSERINDO DADOS NA TABELA TBCONTATOS SEGUINDO ESTRUTURA DE CRIAÇÃO
INSERT INTO TBCONTATOS VALUES ('Rua 1','Familía','José da Silva');
INSERT INTO TBCONTATOS VALUES ('Rua 3','Amigo','Jorge');

--CRIANDO TABELA COM CHAVE ESTRANGEIRA TBEMAIL

CREATE TABLE TBEMAILS
(
   ID_EMAIL INT PRIMARY KEY NOT NULL IDENTITY (1,1),
   COD_CONTATO INT REFERENCES TBCONTATOS(ID_CONTATO) NOT NULL,
   EMAIL VARCHAR (35) NOT NULL
);

--BUSCA DE DADOS NA TABELA TBEMAILS
SELECT *FROM TBEMAILS;

--APAGAR TABELA
DROP TABLE TBEMAILS;

--INSERINDO DADOS NA TABELA TBEMAIL SEM SEGUIR ESTRUTURA DE CRAIÇÃO
INSERT INTO TBEMAILS (COD_CONTATO, EMAIL) VALUES (2, 'josedasilva123@gmail.com');
INSERT INTO TBEMAILS (COD_CONTATO, EMAIL) VALUES (2, 'josedasilva@gmail.com');
INSERT INTO TBEMAILS (COD_CONTATO, EMAIL) VALUES (1, 'maria@bol.com');

--CRAINDO TABELA TBFONE
CREATE TABLE TBTELEFONES
(
  ID_TELEFONE INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  COD_CONTATO INT REFERENCES TBCONTATOS(ID_CONTATO) NOT NULL,
  TELEFONE VARCHAR (15) NOT NULL 
);

--BUSCA DE DADOS DA TABELA TBTELEFONES
SELECT *FROM TBTELEFONES;

--APAGAR DADOS DA TABELA
DROP TABLE TBTELEFONES;

--INSERINDO DADOS NA TABELA TBTELEFONES
INSERT INTO TBTELEFONES (COD_CONTATO, TELEFONE) VALUES (3, '(17)981213455');
INSERT INTO TBTELEFONES (COD_CONTATO, TELEFONE) VALUES (3, '(17)21324533');
INSERT INTO TBTELEFONES (COD_CONTATO, TELEFONE) VALUES (2, '(17)31214521');
